"""archive5

Revision ID: 41cf3886aa39
Revises: 
Create Date: 2024-07-16 10:53:24.416613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cf3886aa39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=False),
    sa.Column('old_email', sa.String(length=120), nullable=False),
    sa.Column('old_password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('old_email'),
    sa.UniqueConstraint('old_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archive')
    # ### end Alembic commands ###
