"""added is_active,attempts and table complains

Revision ID: cecccc004244
Revises: 3fb17eaf60a4
Create Date: 2024-07-17 00:21:12.490614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecccc004244'
down_revision = '3fb17eaf60a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('failure_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('failure_attempts')
        batch_op.drop_column('is_active')

    op.drop_table('complains')
    # ### end Alembic commands ###
